#!/bin/bash

############################
# Author: Bhargavi B
# Date: Sept 14 2024

# Version: v1

# This script will report the AWS resource usage
###############################

set -x

#resource to track
#AWS S3
#AWS Ec2
#AWS Lambda
#AWS IAM Users


#list s3 buckets
echo "Print list of s3 buckets"
aws s3 ls

#list ec2 instances
echo "Print list of ec2 instances"
aws ec2 describe-instances

#list lambda
echo "Print list of Lambda"
aws lambda list-functions

#list iam users
echo "Print list of iam users"
aws iam list-users
                                                                                                                      35,1          Bot
