#!/bin/bash

#####################
# Author : Bhargavi B
# Date : 07/09/2024
#
# This script outputs the node health
#
# Version: v1
#####################

set -x # debug mode
set -e # exit the script where there is an error
set -o pipefail

df -h


free -g


nproc

ps -ef
